// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUlSdqj_-DQxymS5HgsqnzPTTsLxlblHU',
    appId: '1:457365981893:web:2fb12e72834fd7de27feac',
    messagingSenderId: '457365981893',
    projectId: 'flutter-chat-app-aa42a',
    authDomain: 'flutter-chat-app-aa42a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-aa42a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSFc4l6ezh9McNu6fBr81Le9AtFFGI7g',
    appId: '1:457365981893:android:c60505dfb1a41aaf27feac',
    messagingSenderId: '457365981893',
    projectId: 'flutter-chat-app-aa42a',
    storageBucket: 'flutter-chat-app-aa42a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Z0SuMg31Jc04gDB-N9JtHBEZdoZH6lE',
    appId: '1:457365981893:ios:600dedb0b632e01327feac',
    messagingSenderId: '457365981893',
    projectId: 'flutter-chat-app-aa42a',
    storageBucket: 'flutter-chat-app-aa42a.appspot.com',
    iosBundleId: 'com.example.uFireChatApp',
  );
}
